"""Render a saved contract analysis as a downloadable report.

Three formats are supported:

- ``txt`` — plain text, no dependencies.
- ``doc`` — Word-compatible HTML (MIME ``application/msword``). Word,
  LibreOffice, and Google Docs all open it with formatting intact.
- ``pdf`` — generated with fpdf2. fpdf2's built-in fonts are latin-1 only,
  so text goes through ``_pdf_text`` which maps common Unicode characters
  found in Indian contracts (₹, curly quotes, dashes) to safe equivalents.
"""

import re
from datetime import datetime
from html import escape

from fpdf import FPDF

from backend.models import AnalysisResult

REPORT_TITLE = "Contract Analysis Report"
DISCLAIMER = (
    "Generated by Advocate Contracts. This is an AI-assisted analysis "
    "for informational purposes only and is not legal advice."
)

_FILENAME_UNSAFE = re.compile(r"[^A-Za-z0-9._-]+")

# fpdf2 core fonts encode latin-1 — map frequent non-latin-1 characters.
_PDF_CHAR_MAP = {
    "₹": "Rs.",
    "€": "EUR",
    "£": "GBP",
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
    "–": "-",
    "—": "-",
    "•": "*",
    "…": "...",
    " ": " ",
}


def report_basename(contract_name: str) -> str:
    """Filesystem-safe base filename for downloads, derived from the contract."""
    stem = contract_name.rsplit(".", 1)[0] if "." in contract_name else contract_name
    safe = _FILENAME_UNSAFE.sub("-", stem).strip("-._")
    return f"{safe or 'contract'}-analysis"


def _format_date(iso_value: str) -> str:
    try:
        return datetime.fromisoformat(iso_value).strftime("%d %b %Y, %H:%M")
    except (TypeError, ValueError):
        return iso_value or "Unknown date"


def _pdf_text(value: object) -> str:
    """Make arbitrary text safe for fpdf2's latin-1 core fonts."""
    text = str(value)
    for char, replacement in _PDF_CHAR_MAP.items():
        text = text.replace(char, replacement)
    return text.encode("latin-1", "replace").decode("latin-1")


# --- Plain text --------------------------------------------------------------


def build_txt(analysis: AnalysisResult, contract_name: str) -> str:
    lines = [
        REPORT_TITLE.upper(),
        "=" * len(REPORT_TITLE),
        "",
        f"Contract:           {contract_name}",
        f"Contract type:      {analysis.contract_type or 'Unknown'}",
        f"Analyzed:           {_format_date(analysis.analysis_date)}",
        f"Overall risk level: {analysis.overall_risk_level.value.upper()}",
        "",
        "SUMMARY",
        "-" * 7,
        analysis.summary or "(none)",
        "",
        f"KEY CLAUSES ({len(analysis.key_clauses)})",
        "-" * 11,
    ]
    for index, clause in enumerate(analysis.key_clauses, start=1):
        standard = "standard" if clause.is_standard else "non-standard"
        lines += [
            f"{index}. {clause.clause_title} [{standard}]",
            f"   Clause: {clause.clause_text}",
            f"   Meaning: {clause.explanation}",
            "",
        ]
    if not analysis.key_clauses:
        lines += ["(none identified)", ""]

    lines += [f"RISK FLAGS ({len(analysis.risk_flags)})", "-" * 10]
    for index, risk in enumerate(analysis.risk_flags, start=1):
        lines += [
            f"{index}. {risk.risk_title} [{risk.risk_level.value.upper()}]",
            f"   Risk: {risk.description}",
            f"   Recommendation: {risk.recommendation}",
        ]
        if risk.clause_reference:
            lines.append(f"   Refers to: {risk.clause_reference}")
        lines.append("")
    if not analysis.risk_flags:
        lines += ["(none identified)", ""]

    lines += [f"RECOMMENDATIONS ({len(analysis.recommendations)})", "-" * 15]
    lines += [f"- {item}" for item in analysis.recommendations] or ["(none)"]
    lines += ["", DISCLAIMER, ""]
    return "\n".join(lines)



# --- Word-compatible HTML (.doc) ---------------------------------------------


def build_doc(analysis: AnalysisResult, contract_name: str) -> str:
    def item(text: object) -> str:
        return escape(str(text))

    clauses_html = "".join(
        f"<h3>{i}. {item(c.clause_title)} "
        f"<span class='tag'>({'standard' if c.is_standard else 'non-standard'})</span></h3>"
        f"<p><b>Clause:</b> {item(c.clause_text)}</p>"
        f"<p><b>Meaning:</b> {item(c.explanation)}</p>"
        for i, c in enumerate(analysis.key_clauses, start=1)
    ) or "<p>None identified.</p>"

    risks_html = "".join(
        f"<h3>{i}. {item(r.risk_title)} "
        f"<span class='tag'>{item(r.risk_level.value.upper())}</span></h3>"
        f"<p><b>Risk:</b> {item(r.description)}</p>"
        f"<p><b>Recommendation:</b> {item(r.recommendation)}</p>"
        + (f"<p><b>Refers to:</b> {item(r.clause_reference)}</p>" if r.clause_reference else "")
        for i, r in enumerate(analysis.risk_flags, start=1)
    ) or "<p>None identified.</p>"

    recommendations_html = "".join(
        f"<li>{item(rec)}</li>" for rec in analysis.recommendations
    ) or "<li>None.</li>"

    return f"""<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
<meta charset="utf-8">
<title>{escape(REPORT_TITLE)} — {escape(contract_name)}</title>
<style>
  body {{ font-family: Calibri, Arial, sans-serif; color: #1f2937; }}
  h1 {{ font-size: 22pt; margin-bottom: 4pt; }}
  h2 {{ font-size: 14pt; border-bottom: 1px solid #d1d5db; padding-bottom: 2pt; margin-top: 18pt; }}
  h3 {{ font-size: 11.5pt; margin-bottom: 2pt; }}
  p, li {{ font-size: 10.5pt; }}
  .meta {{ color: #6b7280; }}
  .tag {{ font-size: 9pt; color: #6b7280; font-weight: normal; }}
  .disclaimer {{ margin-top: 24pt; font-size: 9pt; color: #9ca3af; }}
</style>
</head>
<body>
<h1>{escape(REPORT_TITLE)}</h1>
<p class="meta">
  <b>Contract:</b> {escape(contract_name)}<br>
  <b>Contract type:</b> {item(analysis.contract_type or 'Unknown')}<br>
  <b>Analyzed:</b> {item(_format_date(analysis.analysis_date))}<br>
  <b>Overall risk level:</b> {item(analysis.overall_risk_level.value.upper())}
</p>

<h2>Summary</h2>
<p>{item(analysis.summary or '(none)')}</p>

<h2>Key Clauses ({len(analysis.key_clauses)})</h2>
{clauses_html}

<h2>Risk Flags ({len(analysis.risk_flags)})</h2>
{risks_html}

<h2>Recommendations ({len(analysis.recommendations)})</h2>
<ul>{recommendations_html}</ul>

<p class="disclaimer">{escape(DISCLAIMER)}</p>
</body>
</html>
"""


# --- PDF (fpdf2) ---------------------------------------------------------------


def build_pdf(analysis: AnalysisResult, contract_name: str) -> bytes:
    pdf = FPDF(format="A4")
    pdf.set_margins(18, 18, 18)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    def heading(text: object, size: int = 13) -> None:
        pdf.set_font("helvetica", "B", size)
        pdf.set_text_color(31, 41, 55)
        pdf.multi_cell(0, 8, _pdf_text(text), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    def body(text: object, size: int = 10, bold: bool = False) -> None:
        pdf.set_font("helvetica", "B" if bold else "", size)
        pdf.set_text_color(17, 24, 39)
        pdf.multi_cell(0, 5.5, _pdf_text(text), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Title block
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(17, 24, 39)
    pdf.multi_cell(0, 10, _pdf_text(REPORT_TITLE), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(
        0,
        6,
        _pdf_text(
            f"Contract: {contract_name}\n"
            f"Contract type: {analysis.contract_type or 'Unknown'}\n"
            f"Analyzed: {_format_date(analysis.analysis_date)}\n"
            f"Overall risk level: {analysis.overall_risk_level.value.upper()}"
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(4)

    heading("Summary")
    body(analysis.summary or "(none)")

    heading(f"Key clauses ({len(analysis.key_clauses)})")
    if analysis.key_clauses:
        for index, clause in enumerate(analysis.key_clauses, start=1):
            standard = "standard" if clause.is_standard else "non-standard"
            body(f"{index}. {clause.clause_title} [{standard}]", bold=True)
            body(f"Clause: {clause.clause_text}")
            body(f"Meaning: {clause.explanation}")
    else:
        body("(none identified)")

    heading(f"Risk flags ({len(analysis.risk_flags)})")
    if analysis.risk_flags:
        for index, risk in enumerate(analysis.risk_flags, start=1):
            body(f"{index}. {risk.risk_title} [{risk.risk_level.value.upper()}]", bold=True)
            body(f"Risk: {risk.description}")
            body(f"Recommendation: {risk.recommendation}")
            if risk.clause_reference:
                body(f"Refers to: {risk.clause_reference}")
    else:
        body("(none identified)")

    heading(f"Recommendations ({len(analysis.recommendations)})")
    if analysis.recommendations:
        for item in analysis.recommendations:
            body(f"* {item}")
    else:
        body("(none)")

    pdf.ln(4)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(156, 163, 175)
    pdf.multi_cell(0, 5, _pdf_text(DISCLAIMER), new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())

